require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - node_modules/**/*
    - config.ru
    - Guardfile
    - Rakefile
Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 30

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 50
  ExcludedMethods: ['describe', 'context']

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Documentation:
  Enabled: false
